project_id                      = "my-gcp-project-id"
wlid_pool_id                    = "my-pool-id"
wlid_pool_display_name          = "My pool"
wlid_pool_provider_id           = "my-github-provider-id"
wlid_pool_provider_display_name = "My Github Provider"
wlid_pool_provider_repo_owner   = "myname"
wlid_sa                         = "my-github-actions-sa"
wlid_sa_name                    = "My GitHub Actions Service Account"
