name: "Sample GCP workflow"

on:
  workflow_dispatch:

env:
  PROJECT_ID: bluebirz-playground
  WLID_PROVIDER: projects/390283753510/locations/global/workloadIdentityPools/bluebirz-github-pool/providers/github-provider
  SA_EMAIL: github-actions-sa@bluebirz-playground.iam.gserviceaccount.com

permissions:
  id-token: write
  contents: read

jobs:
  prepare:
    name: "prepare"
    runs-on: ubuntu-latest
    steps:
      - name: Debug OIDC Claims
        uses: github/actions-oidc-debugger@main
        with:
          audience: "${{ github.server_url }}/${{ github.repository_owner }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WLID_PROVIDER }}
          project_id: ${{ env.PROJECT_ID }}
          service_account: ${{ env.SA_EMAIL }}

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.PROJECT_ID }}

      - name: test
        run: >
          bq show --format=prettyjson --schema test.ncd_test
