name: "Sample GCP workflow"

on:
  workflow_dispatch:

env:
  PROJECT_ID: <project_id>
  WLID_PROVIDER: projects/<project_number>/locations/global/workloadIdentityPools/<pool_id>/providers/<provider_id>
  SA_EMAIL: <service_account>@<project_id>.iam.gserviceaccount.com

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WLID_PROVIDER }}
          project_id: ${{ env.PROJECT_ID }}
          service_account: ${{ env.SA_EMAIL }}

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: List files
        run: >
          gcloud storage ls ...
